apiVersion: batch/v1 
kind: Job 
metadata:
  name: node-app-job-1
spec:
  #completions: 8
  parallelism: 8
  template:
    spec:
      containers:
      - name: node-app-job 
        image: alpine 
        command: ["echo","welcome to my node app"]
      restartPolicy: Never