apiVersion: batch/v1 
kind: Job 
metadata:
  name: node-app-job
spec:
  completions: 8
  parallelism: 8 #the same job will be executed by 8 pod
  template:
    spec:
      containers:
      - name: node-app-job 
        image: alpine 
        command: ["echo","welcome to my node app"]
      restartPolicy: Never