apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-mysql
  template:
    metadata:
      labels:
        app: myapp-mysql 
    spec:
      containers:
      - name: myapp
        image: mysql:5.6
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: db-password 

        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-volume
            mountPath: /var/lib/mysql
          - name: usermgmt-db-script
            mountPath: /docker-entrypoint-initdb.d
      volumes: 
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: task-pv-claim
        - name: usermgmt-db-script
          configMap: 
            name: user-management-script
    
