apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volum
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #read #readwritemany
  hostPath:
    path: /mnt/data
